package com.data_management;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Stream;

/**
 * Reads patient data from text files generated by FileOutputStrategy and stores
 * it in DataStorage.
 */
public class FileDataReader implements DataReader {

    private String directory;

    /**
     * Constructs a FileDataReader that reads files from the specified directory.
     *
     * @param directory the path to the directory containing patient data files
     */
    public FileDataReader(String directory) {
        this.directory = directory;
    }

    /**
     * Reads all .txt files in the configured directory and stores the parsed
     * patient data into the provided DataStorage instance.
     *
     * @param dataStorage the storage where parsed data will be stored
     * @throws IOException if the directory cannot be read
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        Path dirPath = Paths.get(directory);
        try (Stream<Path> files = Files.list(dirPath)) {
            files.filter(p -> p.toString().endsWith(".txt"))
                 .forEach(file -> {
                     try {
                         readFile(file, dataStorage);
                     } catch (IOException e) {
                         System.err.println("Error reading file: " + file + " - " + e.getMessage());
                     }
                 });
        }
    }

    private void readFile(Path file, DataStorage dataStorage) throws IOException {
        try (BufferedReader reader = Files.newBufferedReader(file)) {
            String line;
            while ((line = reader.readLine()) != null) {
                parseLine(line, dataStorage);
            }
        }
    }

    // Expected format: Patient ID: 1, Timestamp: 123456, Label: HeartRate, Data: 75.5
    private void parseLine(String line, DataStorage dataStorage) {
        try {
            String[] parts = line.split(", ");
            int patientId = Integer.parseInt(parts[0].split(": ")[1].trim());
            long timestamp = Long.parseLong(parts[1].split(": ")[1].trim());
            String label = parts[2].split(": ")[1].trim();
            String dataStr = parts[3].split(": ")[1].trim();

            double value;
            if (dataStr.equals("triggered")) {
                value = 1.0;
            } else if (dataStr.equals("resolved")) {
                value = 0.0;
            } else {
                value = Double.parseDouble(dataStr.replace("%", ""));
            }

            dataStorage.addPatientData(patientId, value, label, timestamp);
        } catch (Exception e) {
            System.err.println("Skipping malformed line: " + line);
        }
    }
}
